version: '3'
services:
  sonic-server-simple:
    image: "zhouyixun/sonic-server-simple:v1.2.0-beta3"
    environment:
      #以下为MySql配置，localhost请替换为自己MySql服务的ipv4地址
      - MYSQL_HOST=localhost
      - MYSQL_PORT=3306
      - MYSQL_DATABASE=sonic
      - MYSQL_USERNAME=root
      - MYSQL_PASSWORD=Sonic!@#123
      #在服务器部署的话，localhost改为服务器ip，port更改为sonic-server-simple暴露的port（一般不变）
      - SONIC_API_HOST=localhost
      - SONIC_API_PORT=8094
      - SONIC_NETTY_PORT=8095
      #token加密的key值
      - SECRET_KEY=sonic
      #身份验证token有效天数
      - EXPIRE_DAY=14
      #前端页面访问地址，不填默认为http://localhost:3000
      - CLIENT_HOST=http://localhost:3000
      #文件保留天数（指测试过程产生的文件，包括图片、录像等等）
      - FILE_KEEP_DAY=60
      #测试结果保留天数
      - RESULT_KEEP_DAY=60
      #以下均为Cron表达式
      #清理文件定时任务
      - FILE_CRON=0 0 12 * * ?
      #清理测试结果定时任务
      - RESULT_CRON=0 0 12 * * ?
      #发送日报定时任务
      - DAY_CRON=0 0 10 * * ?
      #发送周报定时任务
      - WEEK_CRON=0 0 10 ? * Mon
    networks:
      - sonic-network
    volumes:
      - files:/keepFiles/
      - files:/imageFiles/
      - files:/recordFiles/
      - files:/packageFiles/
      - files:/logs/
    ports:
      - "8094:8094"
      - "8095:8095"
  sonic-client-web:
    image: "zhouyixun/sonic-client-web:v1.2.0-beta3"
    environment:
      #在服务器部署的话，localhost改为服务器ip，port更改为sonic-server-simple暴露的port（一般不变）
      - SONIC_API_HOST=localhost
      - SONIC_API_PORT=8094
    networks:
      - sonic-network
    ports:
      - "3000:80"

volumes:
  files:

networks:
  sonic-network:
    driver: bridge