server:
  port: 8094

spring:
  application:
    name: sonic-server-simple
    des: "Sonic云真机测试平台 - 单机版"
  servlet:
    multipart:
      maxFileSize: -1
      maxRequestSize: -1
  quartz:
    properties:
      org:
        quartz:
          scheduler:
            instanceName: SonicQuartz
            instanceId: AUTO
          jobStore:
            isClustered: true
    job-store-type: jdbc
    jdbc:
      initialize-schema: never
  datasource:
    initialization-mode: always
    schema:
      - classpath:data.sql
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sonic?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC&autoReconnect=true&serverTimezone=GMT%2b8
    username: root
    password: Sonic!@#123
# mybatis-plus配置
mybatis-plus:
  mapper-locations: classpath:mapping/*.xml, classpath*:com/gitee/sunchenbin/mybatis/actable/mapping/*/*.xml
  global-config:
    # 是否显示mybatis-plus图标
    banner: false
  configuration:
    # 关闭二级缓存
    cache-enabled: false
    # 关闭一级缓存
    localCacheScope: STATEMENT
    # sql日志
    # log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
# 数据库自动生成表
actable:
  model:
    pack: org.cloud.sonic.simple.models.domain
  table:
    auto: update
  database:
    type: mysql

gateway:
  host: "http://localhost:8094"
  secret: sonic
  expireDay: 14

sonic:
  netty:
    port: 8095
  jobs:
    fileCron: 0 0 12 * * ?
    resultCron: 0 0 12 * * ?
    dayReportCron: 0 0 10 * * ?
    weekReportCron: 0 0 10 ? * Mon
    filesKeepDay: 60
    resultsKeepDay: 60

robot:
  client:
    host: "http://localhost:3000"
  img:
    success: "https://gitee.com/sonic-cloud/sonic-cloud/raw/master/src/assets/suc.png"
    warning: "https://gitee.com/sonic-cloud/sonic-cloud/raw/master/src/assets/warn.png"
    error: "https://gitee.com/sonic-cloud/sonic-cloud/raw/master/src/assets/fail.png"

knife4j:
  enable: true
  setting:
    enableHost: true
    enableHostText: "http://localhost:8094"
    enableFooter: false
    enableFooterCustom: true
    footerCustomContent: MIT License | Copyright 2021 - [SonicCloudOrg/sonic-server](https://github.com/SonicCloudOrg/sonic-server/blob/main/LICENSE)

logging:
  file:
    name: logs/${spring.application.name}.log
  logback:
    rollingpolicy:
      clean-history-on-start: true
      max-history: 3